{
  "comments": [
    {
      "key": {
        "uuid": "1a106d94_1aaf9795",
        "filename": "midolman/src/main/scala/org/midonet/midolman/tools/MmCtl.scala",
        "patchSetId": 4
      },
      "lineNbr": 79,
      "author": {
        "id": 1002731
      },
      "writtenOn": "2015-04-28T10:04:30Z",
      "side": 1,
      "message": "should this have a case _ too? zoom at least can throw a variety of other exceptions.\n\nSame for other exceptions below. Actually, I guess it\u0027d make sense to have bindPort and unbindPort return a Try[Unit], then factor out the SUCCESS.getResult plus all the duplicate exception management code to a single place.",
      "revId": "26d1e4ba3d11b4114f5e4f0dceacdab0bc414e78",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a106d94_7a7e8b1a",
        "filename": "midolman/src/main/scala/org/midonet/midolman/tools/MmCtl.scala",
        "patchSetId": 4
      },
      "lineNbr": 132,
      "author": {
        "id": 1002731
      },
      "writtenOn": "2015-04-28T10:04:30Z",
      "side": 1,
      "message": "alignment",
      "revId": "26d1e4ba3d11b4114f5e4f0dceacdab0bc414e78",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a106d94_1a867713",
        "filename": "midolman/src/main/scala/org/midonet/midolman/tools/MmCtl.scala",
        "patchSetId": 4
      },
      "lineNbr": 197,
      "author": {
        "id": 1002731
      },
      "writtenOn": "2015-04-28T10:04:30Z",
      "side": 1,
      "message": "Maybe drop this, and add a | IllegalArgumentException to the tryCatch in Main",
      "range": {
        "startLine": 194,
        "startChar": 8,
        "endLine": 197,
        "endChar": 9
      },
      "revId": "26d1e4ba3d11b4114f5e4f0dceacdab0bc414e78",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a106d94_5a946f42",
        "filename": "midolman/src/main/scala/org/midonet/midolman/tools/MmCtl.scala",
        "patchSetId": 4
      },
      "lineNbr": 252,
      "author": {
        "id": 1002731
      },
      "writtenOn": "2015-04-28T10:04:30Z",
      "side": 1,
      "message": "style",
      "range": {
        "startLine": 251,
        "startChar": 12,
        "endLine": 252,
        "endChar": 13
      },
      "revId": "26d1e4ba3d11b4114f5e4f0dceacdab0bc414e78",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a106d94_ba9da368",
        "filename": "midolman/src/main/scala/org/midonet/midolman/tools/MmCtl.scala",
        "patchSetId": 4
      },
      "lineNbr": 255,
      "author": {
        "id": 1002731
      },
      "writtenOn": "2015-04-28T10:04:30Z",
      "side": 1,
      "message": "ditto",
      "revId": "26d1e4ba3d11b4114f5e4f0dceacdab0bc414e78",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "1a106d94_3a81b3fb",
        "filename": "midolman/src/main/scala/org/midonet/midolman/tools/MmCtl.scala",
        "patchSetId": 4
      },
      "lineNbr": 268,
      "author": {
        "id": 1002731
      },
      "writtenOn": "2015-04-28T10:04:30Z",
      "side": 1,
      "message": "move up to grab just the section that might throw this exception?",
      "range": {
        "startLine": 266,
        "startChar": 8,
        "endLine": 268,
        "endChar": 37
      },
      "revId": "26d1e4ba3d11b4114f5e4f0dceacdab0bc414e78",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}