{
  "comments": [
    {
      "key": {
        "uuid": "baa041b7_d4b8b513",
        "filename": "midonet-util/src/main/java/org/midonet/util/process/MonitoredDaemonProcess.java",
        "patchSetId": 8
      },
      "lineNbr": 49,
      "author": {
        "id": 1003555
      },
      "writtenOn": "2016-09-19T12:58:16Z",
      "side": 1,
      "message": "It\u0027d be better to give this an argument which is the exception why it failed. Maybe use a java.util.function.Consumer\u003cT\u003e?",
      "range": {
        "startLine": 49,
        "startChar": 60,
        "endLine": 49,
        "endChar": 68
      },
      "revId": "ae1756106e82094af61f1f04b9c9a04b6b44cca7",
      "serverId": "d5d70762-12d0-45a1-890d-524b12d3f735",
      "unresolved": false
    }
  ]
}